name: Test GCE Prefect Agent
on:
  workflow_dispatch:

jobs:
  prefect_agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: custom
        uses: ./.github/actions/deploy-agent
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          gcp_sa_email: ${{ secrets.GCP_SA_EMAIL }}
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          gcp_project_id: "prefect-community"
          region: "us-east1"  # optional
          zone: "us-east1-b"  # optional
          artifact_repository: "prefect"  # optional
          machine_type: "e2-micro"  # optional
          machine_name: "prefect-cloud-vm"  # optional
